//
// Created by nkk on 2025/10/26.
//

#ifndef TFFINFER_GRAPH_BASEDEFINE_H
#define TFFINFER_GRAPH_BASEDEFINE_H
namespace tff::core::graph {
    enum TffOpType {
        TFF_OP_NONE = 0,

        TFF_OP_DUP,
        TFF_OP_ADD,
        TFF_OP_ADD_ID,
        TFF_OP_ADD1,
        TFF_OP_ACC,
        TFF_OP_SUB,
        TFF_OP_MUL,
        TFF_OP_DIV,
        TFF_OP_SQR,
        TFF_OP_SQRT,
        TFF_OP_LOG,
        TFF_OP_SIN,
        TFF_OP_COS,
        TFF_OP_SUM,
        TFF_OP_SUM_ROWS,
        TFF_OP_MEAN,
        TFF_OP_ARGMAX,
        TFF_OP_COUNT_EQUAL,
        TFF_OP_REPEAT,
        TFF_OP_REPEAT_BACK,
        TFF_OP_CONCAT,
        TFF_OP_SILU_BACK,
        TFF_OP_NORM, // normalize
        TFF_OP_RMS_NORM,
        TFF_OP_RMS_NORM_BACK,
        TFF_OP_GROUP_NORM,
        TFF_OP_L2_NORM,

        TFF_OP_MUL_MAT,
        TFF_OP_MUL_MAT_ID,
        TFF_OP_OUT_PROD,

        TFF_OP_SCALE,
        TFF_OP_SET,
        TFF_OP_CPY,
        TFF_OP_CONT,
        TFF_OP_RESHAPE,
        TFF_OP_VIEW,
        TFF_OP_PERMUTE,
        TFF_OP_TRANSPOSE,
        TFF_OP_GET_ROWS,
        TFF_OP_GET_ROWS_BACK,
        TFF_OP_SET_ROWS,
        TFF_OP_DIAG,
        TFF_OP_DIAG_MASK_INF,
        TFF_OP_DIAG_MASK_ZERO,
        TFF_OP_SOFT_MAX,
        TFF_OP_SOFT_MAX_BACK,
        TFF_OP_ROPE,
        TFF_OP_ROPE_BACK,
        TFF_OP_CLAMP,
        TFF_OP_CONV_TRANSPOSE_1D,
        TFF_OP_IM2COL,
        TFF_OP_IM2COL_BACK,
        TFF_OP_IM2COL_3D,
        TFF_OP_CONV_2D,
        TFF_OP_CONV_3D,
        TFF_OP_CONV_2D_DW,
        TFF_OP_CONV_TRANSPOSE_2D,
        TFF_OP_POOL_1D,
        TFF_OP_POOL_2D,
        TFF_OP_POOL_2D_BACK,
        TFF_OP_UPSCALE,
        TFF_OP_PAD,
        TFF_OP_PAD_REFLECT_1D,
        TFF_OP_ROLL,
        TFF_OP_ARANGE,
        TFF_OP_TIMESTEP_EMBEDDING,
        TFF_OP_ARGSORT,
        TFF_OP_LEAKY_RELU,

        TFF_OP_FLASH_ATTN_EXT,
        TFF_OP_FLASH_ATTN_BACK,
        TFF_OP_SSM_CONV,
        TFF_OP_SSM_SCAN,
        TFF_OP_WIN_PART,
        TFF_OP_WIN_UNPART,
        TFF_OP_GET_REL_POS,
        TFF_OP_ADD_REL_POS,
        TFF_OP_RWKV_WKV6,
        TFF_OP_GATED_LINEAR_ATTN,
        TFF_OP_RWKV_WKV7,

        TFF_OP_UNARY,

        TFF_OP_MAP_CUSTOM1,
        TFF_OP_MAP_CUSTOM2,
        TFF_OP_MAP_CUSTOM3,

        TFF_OP_CUSTOM,

        TFF_OP_CROSS_ENTROPY_LOSS,
        TFF_OP_CROSS_ENTROPY_LOSS_BACK,
        TFF_OP_OPT_STEP_ADAMW,
        TFF_OP_OPT_STEP_SGD,

        TFF_OP_GLU,
        //mem
        TFF_OP_MAP2CPU,
        TFF_OP_MEM_CPY,
        TFF_OP_MEM_REF,
        TFF_OP_EMBEDDING,
        TFF_OP_COUNT,
    };
}
#endif //TFFINFER_BASEDEFINE_H