//
// Created by nkk on 2025/11/3.
//

#include "TFFOPNode.h"

namespace tff::core::graph::op {
    REGISTER_MODULE_OBJECT(MatMulNode, GraphNode, OP_NODE_FLAG, TFF_OP_MUL_MAT);

    REGISTER_MODULE_OBJECT(UploadBuffer, GraphNode, OP_NODE_FLAG, TFF_OP_GET_ROWS);

    REGISTER_MODULE_OBJECT(AddNode, GraphNode, OP_NODE_FLAG, TFF_OP_ADD);

    REGISTER_MODULE_OBJECT(RMSNormNode, GraphNode, OP_NODE_FLAG, TFF_OP_RMS_NORM);

    REGISTER_MODULE_OBJECT(NoneNode, GraphNode, OP_NODE_FLAG, TFF_OP_NONE);

    REGISTER_MODULE_OBJECT(DupNode, GraphNode, OP_NODE_FLAG, TFF_OP_DUP);

    REGISTER_MODULE_OBJECT(SqrNode, GraphNode, OP_NODE_FLAG, TFF_OP_SQR);

    REGISTER_MODULE_OBJECT(SqrtNode, GraphNode, OP_NODE_FLAG, TFF_OP_SQRT);

    REGISTER_MODULE_OBJECT(MulNode, GraphNode, OP_NODE_FLAG, TFF_OP_MUL);

    REGISTER_MODULE_OBJECT(DivNode, GraphNode, OP_NODE_FLAG, TFF_OP_DIV);

    REGISTER_MODULE_OBJECT(ReshapeNode, GraphNode, OP_NODE_FLAG, TFF_OP_RESHAPE);

    REGISTER_MODULE_OBJECT(TransposeNode, GraphNode, OP_NODE_FLAG, TFF_OP_TRANSPOSE);

    REGISTER_MODULE_OBJECT(SoftmaxNode, GraphNode, OP_NODE_FLAG, TFF_OP_SOFT_MAX);

    REGISTER_MODULE_OBJECT(RopeNode, GraphNode, OP_NODE_FLAG, TFF_OP_ROPE);

    REGISTER_MODULE_OBJECT(MapCPUBufferNode, GraphNode, OP_NODE_FLAG, TFF_OP_MAP2CPU);

    REGISTER_MODULE_OBJECT(MemCpyNode, GraphNode, OP_NODE_FLAG, TFF_OP_MEM_CPY);

    REGISTER_MODULE_OBJECT(TokenizeNode, GraphNode, OP_NODE_FLAG, TFF_OP_TOKENIZE);


}
