//
// Created by nkk on 2025/11/3.
//

#include "TFFOPNode.h"

namespace tff::core::graph::op {
    REGISTER_MODULE_OBJECT_PROTOTYPE(MatMulNode, GraphNode, OP_NODE_FLAG, TFF_OP_MUL_MAT);

    REGISTER_MODULE_OBJECT_PROTOTYPE(QuantMatMulNode, GraphNode, OP_NODE_FLAG, TFF_OP_QUANTIZE_MATMUL);

    REGISTER_MODULE_OBJECT_PROTOTYPE(AddNode, GraphNode, OP_NODE_FLAG, TFF_OP_ADD);

    REGISTER_MODULE_OBJECT_PROTOTYPE(RMSNormNode, GraphNode, OP_NODE_FLAG, TFF_OP_RMS_NORM);

    REGISTER_MODULE_OBJECT_PROTOTYPE(RMSNormWNode, GraphNode, OP_NODE_FLAG, TFF_OP_RMS_NORM_W);

    REGISTER_MODULE_OBJECT_PROTOTYPE(MulNode, GraphNode, OP_NODE_FLAG, TFF_OP_MUL);

    REGISTER_MODULE_OBJECT_PROTOTYPE(ReshapeNode, GraphNode, OP_NODE_FLAG, TFF_OP_RESHAPE);

    REGISTER_MODULE_OBJECT_PROTOTYPE(RopeNode, GraphNode, OP_NODE_FLAG, TFF_OP_ROPE);

    REGISTER_MODULE_OBJECT_PROTOTYPE(MapCPUBufferNode, GraphNode, OP_NODE_FLAG, TFF_OP_MAP2CPU);

    REGISTER_MODULE_OBJECT_PROTOTYPE(MemCpyNode, GraphNode, OP_NODE_FLAG, TFF_OP_MEM_CPY);

    REGISTER_MODULE_OBJECT_PROTOTYPE(EmbeddingNode, GraphNode, OP_NODE_FLAG, TFF_OP_EMBEDDING);

    REGISTER_MODULE_OBJECT_PROTOTYPE(FlashAttnNode, GraphNode, OP_NODE_FLAG, TFF_OP_FLASH_ATTN_EXT);

    REGISTER_MODULE_OBJECT_PROTOTYPE(PagedFlashAttnNode, GraphNode, OP_NODE_FLAG, TFF_OP_FLASH_ATTN_PAGED);

    REGISTER_MODULE_OBJECT_PROTOTYPE(PagedFlashAttnRopeNode, GraphNode, OP_NODE_FLAG, TFF_OP_FLASH_ATTN_PAGED_ROPE);

    REGISTER_MODULE_OBJECT_PROTOTYPE(MemRefNode, GraphNode, OP_NODE_FLAG, TFF_OP_MEM_REF);

    REGISTER_MODULE_OBJECT_PROTOTYPE(PreRopeTableNode, GraphNode, OP_NODE_FLAG, TFF_OP_PRE_ROPE_TABLE);

    REGISTER_MODULE_OBJECT_PROTOTYPE(UnaryOPNode, GraphNode, OP_NODE_FLAG, TFF_OP_UNARY);

    REGISTER_MODULE_OBJECT_PROTOTYPE(BinaryOPNode, GraphNode, OP_NODE_FLAG, TFF_OP_BINARY);

    REGISTER_MODULE_OBJECT_PROTOTYPE(MaskOPNode, GraphNode, OP_NODE_FLAG, TFF_OP_ATTN_MASK);

    REGISTER_MODULE_OBJECT_PROTOTYPE(GetOfRowsOPNode, GraphNode, OP_NODE_FLAG, TFF_OP_GET_ROWS);

    REGISTER_MODULE_OBJECT_PROTOTYPE(SetOfRowsOPNode, GraphNode, OP_NODE_FLAG, TFF_OP_SET_ROWS);

    REGISTER_MODULE_OBJECT_PROTOTYPE(QuantNode, GraphNode, OP_NODE_FLAG, TFF_OP_QUANTIZE);

    REGISTER_MODULE_OBJECT_PROTOTYPE(QuantAlignedNode, GraphNode, OP_NODE_FLAG, TFF_OP_QUANTIZE_ALIGNED);

    REGISTER_MODULE_OBJECT_PROTOTYPE(ViewNode, GraphNode, OP_NODE_FLAG, TFF_OP_VIEW);

    REGISTER_MODULE_OBJECT_PROTOTYPE(MemOptNode, GraphNode, OP_NODE_FLAG, TFF_OP_MEM_RECYCLE);

    REGISTER_MODULE_OBJECT_PROTOTYPE(ConvertNode, GraphNode, OP_NODE_FLAG, TFF_OP_CONVERT);

    REGISTER_MODULE_OBJECT_PROTOTYPE(GatherNode, GraphNode, OP_NODE_FLAG, TFF_OP_GATHER);
}
