//
// Created by nkk on 2025/11/3.
//

#include "TFFOPNode.h"

namespace tff::core::graph::op {
    REGISTER_MODULE_OBJECT_PROTOTYPE(MatMulNode, GraphNode, OP_NODE_FLAG, TFF_OP_MUL_MAT);

    REGISTER_MODULE_OBJECT_PROTOTYPE(Q8MatMulNode, GraphNode, OP_NODE_FLAG, TFF_OP_QUANTIZE_Q8_MATMUL);

    REGISTER_MODULE_OBJECT_PROTOTYPE(UploadBuffer, GraphNode, OP_NODE_FLAG, TFF_OP_GET_ROWS);

    REGISTER_MODULE_OBJECT_PROTOTYPE(AddNode, GraphNode, OP_NODE_FLAG, TFF_OP_ADD);

    REGISTER_MODULE_OBJECT_PROTOTYPE(RMSNormNode, GraphNode, OP_NODE_FLAG, TFF_OP_RMS_NORM);

    REGISTER_MODULE_OBJECT_PROTOTYPE(NoneNode, GraphNode, OP_NODE_FLAG, TFF_OP_NONE);

    REGISTER_MODULE_OBJECT_PROTOTYPE(DupNode, GraphNode, OP_NODE_FLAG, TFF_OP_DUP);

    REGISTER_MODULE_OBJECT_PROTOTYPE(SqrNode, GraphNode, OP_NODE_FLAG, TFF_OP_SQR);

    REGISTER_MODULE_OBJECT_PROTOTYPE(SqrtNode, GraphNode, OP_NODE_FLAG, TFF_OP_SQRT);

    REGISTER_MODULE_OBJECT_PROTOTYPE(MulNode, GraphNode, OP_NODE_FLAG, TFF_OP_MUL);

    REGISTER_MODULE_OBJECT_PROTOTYPE(DivNode, GraphNode, OP_NODE_FLAG, TFF_OP_DIV);

    REGISTER_MODULE_OBJECT_PROTOTYPE(ReshapeNode, GraphNode, OP_NODE_FLAG, TFF_OP_RESHAPE);

    REGISTER_MODULE_OBJECT_PROTOTYPE(TransposeNode, GraphNode, OP_NODE_FLAG, TFF_OP_TRANSPOSE);

    REGISTER_MODULE_OBJECT_PROTOTYPE(SoftmaxNode, GraphNode, OP_NODE_FLAG, TFF_OP_SOFT_MAX);

    REGISTER_MODULE_OBJECT_PROTOTYPE(RopeNode, GraphNode, OP_NODE_FLAG, TFF_OP_ROPE);

    REGISTER_MODULE_OBJECT_PROTOTYPE(MapCPUBufferNode, GraphNode, OP_NODE_FLAG, TFF_OP_MAP2CPU);

    REGISTER_MODULE_OBJECT_PROTOTYPE(MemCpyNode, GraphNode, OP_NODE_FLAG, TFF_OP_MEM_CPY);

    REGISTER_MODULE_OBJECT_PROTOTYPE(EmbeddingNode, GraphNode, OP_NODE_FLAG, TFF_OP_EMBEDDING);

    REGISTER_MODULE_OBJECT_PROTOTYPE(FlashAttnNode, GraphNode, OP_NODE_FLAG, TFF_OP_FLASH_ATTN_EXT);

    REGISTER_MODULE_OBJECT_PROTOTYPE(MemRefNode, GraphNode, OP_NODE_FLAG, TFF_OP_MEM_REF);

    REGISTER_MODULE_OBJECT_PROTOTYPE(PreRopeTableNode, GraphNode, OP_NODE_FLAG, TFF_OP_PRE_ROPE_TABLE);

    REGISTER_MODULE_OBJECT_PROTOTYPE(UnaryOPNode, GraphNode, OP_NODE_FLAG, TFF_OP_UNARY);

    REGISTER_MODULE_OBJECT_PROTOTYPE(MaskOPNode, GraphNode, OP_NODE_FLAG, TFF_OP_ATTN_MASK);

    REGISTER_MODULE_OBJECT_PROTOTYPE(GetOfRowsOPNode, GraphNode, OP_NODE_FLAG, TFF_OP_GET_ROWS);

    REGISTER_MODULE_OBJECT_PROTOTYPE(SetOfRowsOPNode, GraphNode, OP_NODE_FLAG, TFF_OP_SET_ROWS);

    REGISTER_MODULE_OBJECT_PROTOTYPE(QuantQ80Node, GraphNode, OP_NODE_FLAG, TFF_OP_QUANTIZE_Q8);

    REGISTER_MODULE_OBJECT_PROTOTYPE(QuantAlignedNode, GraphNode, OP_NODE_FLAG, TFF_OP_QUANTIZE_ALIGNED);

    REGISTER_MODULE_OBJECT_PROTOTYPE(ViewNode, GraphNode, OP_NODE_FLAG, TFF_OP_VIEW);
}
